## Generate `cpi_sim`, the simulated consumer demand data used in the vignette.
##
## THE DATA ARE SIMULATED. Nothing here is a Bureau of Labor Statistics series,
## and no observation corresponds to anything that happened. The goods carry CPI
## expenditure category names because those names make the separability question
## legible to an economist, not because the numbers came from the CPI. Anyone
## reading `data/cpi_sim.rda` should be able to find this script and see exactly
## how every number was made.
##
## Run with: Rscript data-raw/cpi_sim.R

set.seed(20260830)

n_obs <- 36                             # three years of monthly observations

## The true structure. Quantities are generated by two-stage budgeting over
## exactly this partition, so the data are weakly separable in it by
## construction and are not separable in a partition that cuts across it.
groups <- list(
  food           = c("food_at_home", "food_away_from_home"),
  housing        = c("shelter", "utilities", "furnishings"),
  transportation = c("vehicles", "gasoline", "public_transit")
)
goods <- unlist(groups, use.names = FALSE)

## Stage one: CES over the three group quantity indices.
##
## The elasticity of substitution across groups MUST NOT be 1. Two-stage
## Cobb-Douglas budgeting collapses algebraically into a single flat
## Cobb-Douglas over all eight goods, because q_i = theta_g * omega_i * B / p_i
## is just a flat allocation with share theta_g * omega_i. Flat Cobb-Douglas is
## weakly separable in EVERY partition, so data built that way cannot tell a
## true grouping from a scrambled one and is useless for teaching the test.
## This was not a hypothetical: the first version of this script did exactly
## that, and `method = "fw"` correctly reported the scrambled partition as
## separable, because it was.
sigma <- 0.3                            # groups are strong gross complements
target_share <- c(food = 0.20, housing = 0.55, transportation = 0.25)
stopifnot(abs(sum(target_share) - 1) < 1e-12, sigma > 0, sigma != 1)

## `alpha` is calibrated below rather than set by hand. Under CES the
## expenditure share of a group is proportional to alpha_g^sigma * P_g^(1-sigma),
## so picking alpha directly gives shares that depend on the arbitrary price
## levels chosen for each good. Shelter costs 1450 a month and gasoline costs
## 3.05 a gallon, so a hand-set alpha produced a 5 percent food share, which is
## not a number anyone would believe of consumer spending. Inverting for alpha
## at the first observation pins the shares to the plausible values above and
## lets the price process move them from there.

## Stage two: fixed shares within each group.
omega <- list(
  food           = c(food_at_home = 0.60, food_away_from_home = 0.40),
  housing        = c(shelter = 0.65, utilities = 0.20, furnishings = 0.15),
  transportation = c(vehicles = 0.45, gasoline = 0.35, public_transit = 0.20)
)
stopifnot(vapply(omega, function(w) abs(sum(w) - 1) < 1e-12, logical(1)))

## Prices are LEVELS, in dollars per unit, not index numbers rebased to 100.
##
## This is deliberate and it is the one modelling choice in this file worth
## defending. Revealed preference is invariant to scaling every price by a
## common factor, but it is NOT invariant to rescaling goods differently
## against one another, which is exactly what per-series rebasing does. Real
## CPI-style data indexed to 100 in a common base period therefore carries an
## artifact: implied expenditure shares drift apart over the sample for reasons
## that have nothing to do with behaviour. Teaching material should not import
## that artifact, so these are levels.
p0 <- c(
  food_at_home = 3.20, food_away_from_home = 11.50,
  shelter = 1450.00, utilities = 185.00, furnishings = 62.00,
  vehicles = 27500.00, gasoline = 3.05, public_transit = 2.40
)

## Independent drifting prices with month-to-month shocks. Relative prices have
## to move for a revealed preference test to have any power: if the price
## vector only ever scales, no observation is ever revealed preferred to
## another and every partition passes vacuously.
drift <- c(
  food_at_home = 0.0020, food_away_from_home = 0.0028,
  shelter = 0.0031, utilities = 0.0018, furnishings = 0.0009,
  vehicles = 0.0015, gasoline = 0.0012, public_transit = 0.0022
)
shock_sd <- c(
  food_at_home = 0.055, food_away_from_home = 0.040,
  shelter = 0.045, utilities = 0.090, furnishings = 0.050,
  vehicles = 0.035, gasoline = 0.130, public_transit = 0.030
)

price <- matrix(NA_real_, n_obs, length(goods), dimnames = list(NULL, goods))
for (g in goods) {
  steps <- drift[[g]] + stats::rnorm(n_obs, 0, shock_sd[[g]])
  price[, g] <- p0[[g]] * exp(cumsum(steps))
}

## Total expenditure grows with a little noise. Its level does not affect the
## separability verdict, only the scale of the quantities.
budget <- 4200 * exp(stats::rnorm(n_obs, 0, 0.16))

## Two-stage allocation.
##
## Stage two is Cobb-Douglas within each group, so the within-group split
## depends only on within-group prices and on how much the group got. That
## property IS weak separability, imposed here rather than estimated.
##
## Stage one is CES across the three group quantity indices, so how much each
## group gets responds to relative group prices with elasticity sigma. Because
## sigma is not 1, the group structure is real: a partition that cuts across
## these groups does not admit a sub-utility function, which is what makes the
## scrambled partition in the vignette genuinely non-separable rather than
## merely unlucky.
##
## The Cobb-Douglas unit cost index is the exact group price index for stage
## two, so the two stages are mutually consistent and the whole thing is one
## well-defined utility maximisation, not two glued together.
P <- matrix(NA_real_, n_obs, length(groups),
            dimnames = list(NULL, names(groups)))
for (grp in names(groups)) {
  w <- omega[[grp]]
  logP <- rowSums(sweep(log(price[, names(w), drop = FALSE]), 2, w, `*`))
  P[, grp] <- exp(logP)
}

## Calibrate alpha so that the first observation reproduces `target_share`.
## share_g proportional to alpha_g^sigma * P_g^(1-sigma), so invert at t = 1.
alpha <- (target_share / P[1, names(target_share)]^(1 - sigma))^(1 / sigma)
alpha <- alpha / sum(alpha)

## CES expenditure shares across groups.
num <- sweep(P^(1 - sigma), 2, alpha^sigma, `*`)
group_share <- num / rowSums(num)
stopifnot(max(abs(group_share[1, names(target_share)] - target_share)) < 1e-10)

quantity <- matrix(NA_real_, n_obs, length(goods), dimnames = list(NULL, goods))
for (grp in names(groups)) {
  group_budget <- group_share[, grp] * budget
  for (g in groups[[grp]]) {
    quantity[, g] <- omega[[grp]][[g]] * group_budget / price[, g]
  }
}

## Long format, which is what as_demand() consumes.
month <- seq(as.Date("2015-01-01"), by = "month", length.out = n_obs)
cpi_sim <- data.frame(
  month    = rep(month, times = length(goods)),
  good     = factor(rep(goods, each = n_obs), levels = goods),
  price    = as.vector(price),
  quantity = as.vector(quantity),
  stringsAsFactors = FALSE
)
cpi_sim <- cpi_sim[order(cpi_sim$month, cpi_sim$good), ]
rownames(cpi_sim) <- NULL

## Sanity checks. These are assertions about the data-generating process, not
## about the package, so they belong here rather than in tests/.
stopifnot(
  nrow(cpi_sim) == n_obs * length(goods),
  all(cpi_sim$price > 0),
  all(cpi_sim$quantity > 0),
  !anyNA(cpi_sim)
)

## The separability property must hold exactly in the data, and it is checkable
## without any test: WITHIN a group, each good's share of that group's spending
## is constant, because stage two is Cobb-Douglas. That constancy is what weak
## separability in this partition means operationally. If it fails, the
## generator is broken and the vignette would be teaching from data that does
## not have the structure it claims to have.
for (grp in names(groups)) {
  members <- groups[[grp]]
  spend <- price[, members, drop = FALSE] * quantity[, members, drop = FALSE]
  within <- spend / rowSums(spend)
  for (g in members) {
    stopifnot(max(abs(within[, g] - omega[[grp]][[g]])) < 1e-10)
  }
}

## Group shares of TOTAL spending must vary, otherwise sigma has not bitten and
## we are back to flat Cobb-Douglas separable in every partition.
exp_total <- rowSums(price * quantity)
group_spend <- vapply(groups, function(m)
  rowSums(price[, m, drop = FALSE] * quantity[, m, drop = FALSE]) / exp_total,
  numeric(n_obs))
stopifnot(max(apply(group_spend, 2, function(s) diff(range(s)))) > 0.01)
cat("group expenditure shares, range across the sample:\n")
print(round(apply(group_spend, 2, range), 4))

usethis::use_data(cpi_sim, overwrite = TRUE)
