// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rp_relations
List rp_relations(NumericMatrix p, NumericMatrix q, double efficiency);
RcppExport SEXP _weaksep_rp_relations(SEXP pSEXP, SEXP qSEXP, SEXP efficiencySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type efficiency(efficiencySEXP);
    rcpp_result_gen = Rcpp::wrap(rp_relations(p, q, efficiency));
    return rcpp_result_gen;
END_RCPP
}
// scan_violations
IntegerMatrix scan_violations(LogicalMatrix A, LogicalMatrix B, bool skip_diagonal);
RcppExport SEXP _weaksep_scan_violations(SEXP ASEXP, SEXP BSEXP, SEXP skip_diagonalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< bool >::type skip_diagonal(skip_diagonalSEXP);
    rcpp_result_gen = Rcpp::wrap(scan_violations(A, B, skip_diagonal));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_weaksep_rp_relations", (DL_FUNC) &_weaksep_rp_relations, 3},
    {"_weaksep_scan_violations", (DL_FUNC) &_weaksep_scan_violations, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_weaksep(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
