# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rp_relations <- function(p, q, efficiency) {
    .Call(`_weaksep_rp_relations`, p, q, efficiency)
}

scan_violations <- function(A, B, skip_diagonal) {
    .Call(`_weaksep_scan_violations`, A, B, skip_diagonal)
}

